config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'note#index'
  get '/notes', to: "note#index"
  post '/notes', to: "note#create"
  get '/hashtag/:id', to: "note#hashtag"
  patch '/notes', to: "note#update_note"
  get '/delete', to: "note#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
    has_many :hash_tags_notes
    has_many :notes, through: :hash_tags_notes, dependent: :destroy
end

app/models/hash_tags_note.rb
class HashTagsNote < ApplicationRecord
  belongs_to :hash_tag
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
    has_many :hash_tags_notes
    has_many :hash_tags, through: :hash_tags_notes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/note_controller.rb
class NoteController < ApplicationController
    
    def index
        @note = Note.new
        @tags = []
        @count = []
        if HashTagsNote.count != 0
            HashTagsNote.all.order(created_at: "desc").group_by(&:updated_at).values.each do |a|
                if a.length == 1
                    @tags.push(HashTag.find(a[0].hash_tag_id))
                else
                    temp = 0
                  a.each do |hash_tag|
                    count =  HashTagsNote.where(hash_tag_id: hash_tag.hash_tag_id).count
                    @count.push({id: hash_tag.hash_tag_id, count: count})
                  end
                end
            end
            @count.uniq! {|u| u[:id]}
            @sorted = @count.sort_by { |hsh| hsh[:count] }.reverse
            @sorted.each do |hash|
                @tags.push(HashTag.find(hash[:id]))
            end
        end
    end

    def create
        @note = Note.new(note_params)
        if @note.save
          @hash_tag = note_params[:note].split()
          @hash_tag.each do |h_tag|
            if h_tag.start_with? "#"
                @tag = HashTag.find_by(hash_tag: h_tag.downcase)
                if !@tag.present?
                    @note.hash_tags.create(:hash_tag => h_tag.downcase)
                else
                    @note.hash_tags_notes.create(:note_id=> @note.id, hash_tag_id: @tag.id)
                end
            end
          end
          redirect_to notes_path
        end
    end

    def hashtag
        @hashtag = HashTag.find(params[:id])
        if @hashtag.present?
            @notes = @hashtag.notes.order(updated_at: :desc)
            respond_to do |format|
                format.js { render "notes.js.erb" }
            end
        end
    end

    def update_note
        @note = Note.find(note_params[:id])
        if @note.present?
            @note.hash_tags_notes.delete_all
            @tags = []
            @count = []
            if @note.update(note_params)
                @hash_tag = note_params[:note].split()
                @hash_tag.each do |tag|
                    if tag.start_with? "#"
                        @tag = HashTag.find_by(hash_tag: tag.downcase)
                        if !@tag.present?
                            @note.hash_tags.create(:hash_tag => tag.downcase)
                        else
                            @note.hash_tags_notes.create(:note_id=> @note.id, hash_tag_id: @tag.id)
                        end
                    end
                end
                if HashTagsNote.count != 0
                    HashTagsNote.all.order(created_at: "desc").group_by(&:updated_at).values.each do |a|
                        if a.length == 1
                            puts "Hello"
                            @tags.push(HashTag.find(a[0].hash_tag_id))
                        else
                            temp = 0
                          a.each do |hash_tag|
                            count =  HashTagsNote.where(hash_tag_id: hash_tag.hash_tag_id).count
                            @count.push({id: hash_tag.hash_tag_id, count: count})
                          end
                        end
                    end
                    @count.uniq! {|u| u[:id]}
                    @sorted = @count.sort_by { |hsh| hsh[:count] }.reverse
                    @sorted.each do |hash|
                        @tags.push(HashTag.find(hash[:id]))
                    end
                end
                respond_to do |format|
                    format.js {render "index.js.erb" }
                end
            end
        end
    end

    def destroy
        @note = Note.find(params[:id])
        @tags = []
        @count = []
        if @note.present?
            @note.hash_tags.delete_all
            @note.delete
            if HashTagsNote.count != 0
                HashTagsNote.all.order(created_at: "desc").group_by(&:updated_at).values.each do |a|
                    if a.length == 1
                        puts "Hello"
                        @tags.push(HashTag.find(a[0].hash_tag_id))
                    else
                        temp = 0
                      a.each do |hash_tag|
                        count =  HashTagsNote.where(hash_tag_id: hash_tag.hash_tag_id).count
                        @count.push({id: hash_tag.hash_tag_id, count: count})
                      end
                    end
                end
                @count.uniq! {|u| u[:id]}
                @sorted = @count.sort_by { |hsh| hsh[:count] }.reverse
                @sorted.each do |hash|
                    @tags.push(HashTag.find(hash[:id]))
                end
            end
            respond_to do |format|
                format.js {render "update.js.erb" }
            end
        end
        
    end

    private
    def note_params
        params.require(:note).permit(:id, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/views/layouts/_left_col.html.erb
<div class="col-md-3 left_col" id="menu-bar">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" id="panel1"> 
    </div>
    <div class="clearfix">
    
    </div>
    <div id="sidebar-menu" class="main_menu_side hidden_print main_menu">
      <div class="menu_section active">
        <ul class="nav side-menu">
          <li class="<%= 'active' if active == 'Note'  %>">
            <%= link_to notes_path do %>
              <i class="fa fa-home"></i>
                Notes
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav_bar.html.erb
<div class="top_nav">
  <div class="nav_menu nav-white">
    <nav>
      <div class="">
        <% if active == "Note" || active == "Note" %>
          <div class"row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="col-md-6 col-sm-6 col-xs-6">
                <button type="button" class="btn btn-primary create_note_button" data-toggle="modal" data-target="#exampleModal">
                  Create New Note
                </button>
              </div>
            </div>
          </div> 
        <% end %>
      </div>    
    </nav>
  </div>
</div>

<%# modal code  %>
<% if active == "Note" || active == "Note" %>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title note-title" id="exampleModalLabel">Create Note</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for @note, url: notes_path do |f| %>
            <fieldset>
              <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <%= f.text_area :note, class: "", placeholder: "e.g I have great day today #great ......", required: true %>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <center>
                    <%= f.submit "Submit", class:"submit-note" %>
                  </center>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/note/_hash_tag.html.erb
<% tags.each do |tag| %>
  <div class="row">
    <div class="col-md-12 hash_tag_button">
      <%= link_to "/hashtag/#{tag.id}", remote: true do %>
        <h5 class="hash_tah_name" data= "<%= tag.id %>"><%= tag.hash_tag %></h5>
      <% end %>
    </div>
  </div>
<% end %>

app/views/note/_note.html.erb
<div class="row">
    <div class="x_title">
        <h2 class="title"><%=  @hashtag.hash_tag.upcase %> Notes</h2>
        <div class="clearfix"></div>
        <div class="x_content">
            <% notes.each do |note|%>
                <div class="col-md-12" style="margin-top: 20px;">
                    <div class="col-md-7 col-sm-6 col-xs-12">
                        <div class="note_message">
                            <p class="show_note"><%= note.note %></p>
                        </div>
                        <div class="display_form", style ="display:none">
                            <%= form_for note, url: notes_path, method: "patch", remote: true  do |f|%>
                                <fieldset>
                                    <div class="col-md-10 col-sm-10 col-xs-12">
                                        <%= f.text_area :note, class:"note-field", required: true %>
                                        <%= f.hidden_field :id, class:"", value: note.id %>
                                    </div>
                                    <div class="col-md-2 col-sm-2 col-xs-12">
                                        <%= f.submit class:"update-note" %>
                                    </div>
                                </fieldset>
                            <% end %>
                        </div>
                        <button class="cancel_edit" style="display:none">Cancel</button>
                    </div>
                    <div class="col-md-5 col-sm-6 col-xs-12">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="col-md-6 col-sx-6 col-sm-6">
                                    <%= link_to delete_path(id: note), class: "delete_button" , remote: true do %><i class="fa fa-trash"></i><% end %>
                                </div>
                                <div class="col-md-6 col-sx-6 col-sm-6">
                                    <button class="edit-note"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>
<script>
$(".edit-note").on('click', function(){
    $(this).parent().parent().parent().parent().prev().children(".note_message").css("display", "none");
    $(this).parent().parent().parent().parent().prev().children(".display_form").css("display", "block");
    $(this).parent().parent().parent().parent().prev().children(".cancel_edit").css("display", "block");
    $(this).css("display","none");
    $(this).parent().prev().children().css("display","none")
})

$(".cancel_edit").on('click', function(){
    $(this).css("display", "none");
    $(this).prev().css("display", "none");
    $(this).prev().prev(".note_message").css("display", "block")
    $(this).parent().next().children().children().children().children().css("display", "block");
    $(this).parent().next().children().children().children().next().children().css("display", "block");
})
</script>

app/views/note/index.html.erb
<meta name="viewport" content="width= device-width initail-scale=1" />
<body class="dash-body nav-sm" id="dash">
    <div class="container body">
        <div class="main_container">
            <%= render partial: "layouts/left_col", :locals => {active: "Note"} %>
            <%= render partial: "layouts/nav_bar", :locals => {active: "Note"} %>
            <div class="right_col">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            <div class="x_panel tile fixed_height_320">
                                <div class="x_title">
                                    <h2 class="title">HashTags</h2>
                                <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <div class="tags">
                                        <%= render partial: "hash_tag.html.erb", locals: {tags: @tags.uniq} %>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-10 col-sm-6 col-xs-12">
                            <div class="x_panel tile fixed_height_320">
                                <div class="notes">
                                    <% if @notes.present?%>
                                        <%= render partial: "note.html.erb" %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/note/index.js.erb
$('.notes').html("")
$('.tags').html("<%= escape_javascript(render partial: 'hash_tag.html.erb', locals: {tags: @tags.uniq})%>")

app/views/note/notes.js.erb
$('.notes').html("<%= escape_javascript(render partial: 'note.html.erb', locals: {notes: @notes})%>")

app/views/note/update.js.erb
$('.notes').html("")
$('.tags').html("<%= escape_javascript(render partial: 'hash_tag.html.erb', locals: {tags: @tags.uniq})%>")